### ISSUE TITLE
Support Spark-3.0

### ISSUE THREAD

**Issue by marsishandsome** [pingcap/tispark#1173]
### Description
Adapt to Spark-3.0.

### Category
Feature

### Task List
* [x] Study new feature & API in Spark-3.0.
* [x] Code (https://github.com/pingcap/tispark/pull/1493).
* [ ] Pass regression tests.

GanttStart: 2020-07-01
GanttDue: 2020-08-24
GanttProgress: 70%

**Comment by Tongzhenguo** [comment]
期待

**Comment by Tongzhenguo** [comment]
快开发完了吧

**Comment by marsishandsome** [comment]
预计月底能开发完

**Comment by marsishandsome** [comment]
https://github.com/pingcap/tispark/pull/1606
