### ISSUE TITLE
TODO list after normalize pdclient to client-java

### ISSUE THREAD

**Issue by yegetables** [pingcap/tispark#2521]
- `com.pingcap.tikv.util.ConvertUpstreamUtils.isTiKVVersionGreatEqualThanVersion` method: If the upstream changes the method name from `StoreVersion.minTiKVVersion` to `StoreVersion.isTiKVVersionGreatEqualThanVersion`, remove this method and use the upstream method directly. tikv/client-java#647

- TiDBOptions `txnPrewriteBatchSize`,`txnCommitBatchSize`,`writeBufferSize`,`writeThreadPerTask`,`retryCommitSecondaryKey`,`prewriteMaxRetryTimes` are deleted, because these configuration items involve the private constructor of TwoPhaseCommitter. Upstream does not provide a public constructor for use. Temporarily disable the settings of several configuration items to restore the upstream updated configuration. (recovery of documents involved).

- TiFlash cache missing need to fix. #1380 Temporarily fixed in TiSpark.

-  If the retry logic of batchGet is added upstream. Re-check the test result of `batchGetRetryTest`. Restore the test or modify/delete the test tikv/client-java#645

According to the removed class by https://github.com/pingcap/tispark/pull/2491, the following prs need to be paid attention to. we need to judge if they are needed to port to upstream.
<img width="282" alt="image" src="https://user-images.githubusercontent.com/52435083/186579152-913fc296-da1c-4016-811e-5f8a1f671167.png">

-  Retry
    -  Fix txnHeartBeat retry: https://github.com/pingcap/tispark/pull/2304
    -  retry enhancement: https://github.com/pingcap/tispark/pull/1768  https://github.com/pingcap/tispark/pull/2279

- Region manager
   - Fix region manager race: https://github.com/pingcap/tispark/pull/1987

   - Optimize region cache miss：https://github.com/pingcap/tispark/pull/2106 + fix not leader error due to region not invalidatedhttps://github.com/pingcap/tispark/pull/2135

   -  fix region may be missed: https://github.com/pingcap/tispark/pull/2433

- support log desensitization： https://github.com/pingcap/tispark/pull/1798

- Fix ResolveLock not called in Scan API https://github.com/pingcap/tispark/pull/2089

- fix region may be missed https://github.com/pingcap/tispark/pull/2433 （done）

-  Make TiSpark's Explain clearer and easier to read: https://github.com/pingcap/tispark/pull/2439

-  support clustered index https://github.com/pingcap/tispark/pull/1915 ( maintain CoprocessorIterator in TiSpark or upstream ?)

**Comment by shiyuhang0** [comment]
- [ ] TiFlash cache missing need to fix. [TISPARK-488] Fix TiFlash region cache  #1380 Temporarily fixed in TiSpark.
- [ ] If the retry logic of batchGet is added upstream. Re-check the test result of batchGetRetryTest. Restore the test or modify/delete the test https://github.com/tikv/client-java/pull/645
- [ ] Fix txnHeartBeat retry: https://github.com/pingcap/tispark/pull/2304
- [ ] retry enhancement: https://github.com/pingcap/tispark/pull/1768 https://github.com/pingcap/tispark/pull/2279
- [ ] Fix region manager race: https://github.com/pingcap/tispark/pull/1987
- [ ] Optimize region cache miss：https://github.com/pingcap/tispark/pull/2106 + fix not leader error due to region not invalidatedhttps://github.com/https://github.com/pingcap/tispark/pull/2135
- [ ] fix region may be missed: https://github.com/pingcap/tispark/pull/2433
- [ ] support log desensitization： https://github.com/pingcap/tispark/pull/1798
- [ ] Fix ResolveLock not called in Scan API https://github.com/pingcap/tispark/pull/2089
- [ ] Make TiSpark's Explain clearer and easier to read: https://github.com/pingcap/tispark/pull/2439
- [ ] support clustered index https://github.com/pingcap/tispark/pull/1915 ( maintain CoprocessorIterator in TiSpark or upstream ?)

**Comment by shiyuhang0** [comment]
Sometimes, it is difficult to judge which is better (TiSpark or client-java).
In such case, here is two suggestions:
- follow the behavior of TiDB
- reference client-go

**Comment by yegetables** [comment]
> 有时候，很难判断哪个更好（TiSpark或者client-java），比如返回null或者抛出异常；是否为某个错误重试 这种情况，这里有两个建议：
> 
> * 随行 TiDB 的行为
> * 参考客户端

The previous integration test table was not found whether it was caused by a cache miss

I found that the integration test on jenkins seems to be refactored once? (curious)

**Comment by shiyuhang0** [comment]
table not found may not result from the cache miss. it supposed to be fixed in this pr https://github.com/tikv/client-java/pull/670.

integration test should not be refactored.

**Comment by shiyuhang0** [comment]
All things have been done.
