### ISSUE TITLE
Cherry-pick bug fixes to Release-2.1

### ISSUE THREAD

**Issue by birdstorm** [pingcap/tispark#783]
1. List the commits we need to cherry pick, and filter out those which involves batch write.
2. Prepare to update to release-2.1 in correspondence to TiKV/TiDB version
3. Add labels for Pull Requests in future so that we can filter easier.

Together with @zhexuany

**Comment by zhexuany** [comment]
- [ ] Upload codecov report (#704)
- [ ] Make CI use maven m2 cache instead of downloading (#720)
- [ ] Fix concurrent dagrequest issue (#714)
- [ ] Try to use environment CODECOV settings instead of token (#726)
- [ ] Disable downgrade scan temporarily (#730)
- [ ] modify .m2 download stage (#732)
- [ ] Fix downgrade scan (#725)
- [ ] fix integer type default value should be parsed to long (#741)
- [ ] fix index scan on partition table (#735)
- [ ] remove index read conf (#742)
- [ ] Refractor code (#737)
- [ ] fix RegionVerId equals (#739)
- [ ] refactor ScanPlan and TiDAGRequest (#748)
- [ ] fix from spark type (#752)
- [ ] fix KeyNotInRegion may occur when retrieving rows by handle (#755)
- [ ] fix lazy val not working due to incorrect implementation (#749)
- [ ] Trigger format on commit and forbid commit if unformatted (#758)
- [ ] add parallel number for ci test (#762)
- [ ] fix encode value long max (#761)
- [ ] speed ci tests (#766)
- [ ] upgrade jackson version for security alert (#763)
- [ ] remove RedundantBraces in scala format (#769)
- [ ] Fix unsigned bigint in group by columns (#780)
